//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkrainianLiteraure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UkrainianLiteraure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analysis {
            get {
                object obj = ResourceManager.GetObject("analysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Book_Cover {
            get {
                object obj = ResourceManager.GetObject("Book_Cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap books {
            get {
                object obj = ResourceManager.GetObject("books", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coming_document {
            get {
                object obj = ResourceManager.GetObject("coming_document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що є свобода? Добро в ній якеє?
        ///Кажуть, неначе воно золотеє?
        ///Ні ж бо, не злотне: зрівнявши все злото,
        ///Проти свободи воно лиш болото.
        ///О, якби в дурні мені не пошитись,
        ///Щоб без свободи не міг я лишитись.
        ///Слава навіки буде з тобою,
        ///Вольності отче, Богдане-герою!.
        /// </summary>
        internal static string De_libertate {
            get {
                return ResourceManager.GetString("De_libertate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap directory {
            get {
                object obj = ResourceManager.GetObject("directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document {
            get {
                object obj = ResourceManager.GetObject("document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap documentx32 {
            get {
                object obj = ResourceManager.GetObject("documentx32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Енеїда (скорочено)
        ///Іван Котляревський
        ///Частина І
        ///Після того як греки спалили Трою, Еней [один із героїв Троянської війни в античній літературі] з деякими троянцями, зробивши човни, поплив морем. Але Юнона, дружина Зевса [царя богів і людей, бога неба, грому і блискавки], була на стороні греків і дуже не любила Енея:
        ///Давно уже вона хотіла, Його щоб душка полетіла К чортам, і щоб і дух не пах.
        ///Не любила Юнона Енея за те, що був троянцем, і за те, що &quot;мамою Венеру звав&quot;. Венера [давньоримська богиня краси  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eneida {
            get {
                return ResourceManager.GetString("Eneida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Evhen_Malanuk {
            get {
                object obj = ResourceManager.GetObject("Evhen_Malanuk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exam {
            get {
                object obj = ResourceManager.GetObject("exam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap examx24 {
            get {
                object obj = ResourceManager.GetObject("examx24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feather {
            get {
                object obj = ResourceManager.GetObject("feather", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file2 {
            get {
                object obj = ResourceManager.GetObject("file2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grygir_Tytynuk {
            get {
                object obj = ResourceManager.GetObject("Grygir_Tytynuk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hryhoriy_Kvitka {
            get {
                object obj = ResourceManager.GetObject("Hryhoriy_Kvitka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hryhoriy_Skovoroda {
            get {
                object obj = ResourceManager.GetObject("Hryhoriy_Skovoroda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iem_Logo {
            get {
                object obj = ResourceManager.GetObject("iem_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ivan_Bahranyi {
            get {
                object obj = ResourceManager.GetObject("Ivan_Bahranyi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ivan_Drach {
            get {
                object obj = ResourceManager.GetObject("Ivan_Drach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ivan_Franko {
            get {
                object obj = ResourceManager.GetObject("Ivan_Franko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ivan_Karpenko {
            get {
                object obj = ResourceManager.GetObject("Ivan_Karpenko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ivan_Kotlarevskiy {
            get {
                object obj = ResourceManager.GetObject("Ivan_Kotlarevskiy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ivan_Nechui {
            get {
                object obj = ResourceManager.GetObject("Ivan_Nechui", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lesya_Ukrainka {
            get {
                object obj = ResourceManager.GetObject("Lesya_Ukrainka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lina_Kostenko {
            get {
                object obj = ResourceManager.GetObject("Lina_Kostenko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maksym_Rylskiy {
            get {
                object obj = ResourceManager.GetObject("Maksym_Rylskiy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marko_Vovchok {
            get {
                object obj = ResourceManager.GetObject("Marko_Vovchok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маруся (скорочено)
        ///Григорій Квітка-Основ&apos;яненко
        ///Починається повість з філософських роздумів автора про людське життя, про те, що немає на сім світі нічого вічного: сьогодні живеш, а завтра — помер. Кожний батько виховує свою дитину, щоб вона була розумною, доброю. Так само і отець небесний: оберігає людей від усякої напасті, а &quot;коли вже й пошле за гріхи яку біду, то він же і помилує! Тілько покоряйся йому!&quot;
        ///За цими заповідями жив і Наум Дрот. Коли його постигла лиха біда, він хвалив Бога і не вдався в ту [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Marusya {
            get {
                return ResourceManager.GetString("Marusya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu_button {
            get {
                object obj = ResourceManager.GetObject("menu_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mycola_Hvulovui {
            get {
                object obj = ResourceManager.GetObject("Mycola_Hvulovui", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mycola_Kulish {
            get {
                object obj = ResourceManager.GetObject("Mycola_Kulish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mycola_Voronuy {
            get {
                object obj = ResourceManager.GetObject("Mycola_Voronuy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Myhailo_Kocubunskiy {
            get {
                object obj = ResourceManager.GetObject("Myhailo_Kocubunskiy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наталка Полтавка (скорочено)
        ///Іван Котляревський
        ///(П&apos;єса)
        ///І дія
        ///З хати виходить Наталка з відрами на коромислі і, підійшовши до річки, співає пісню &quot;Віють вітри, віють буйні&quot;, яку закінчує словами: &quot;Петре! Вернися до мого серця! Нехай глянуть очі мої на тебе іще раз...&quot;
        ///До неї підходить возний Тетерваковський, гарно одягнений панок. Він починає освідчуватися Наталці: &quot;Не в состоянії поставить на вид тобі сили любві моєй. Когда би я іміл — теє—то як його — столько язиков, сколько артикулов в статуті ілі с [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Natalka_Poltavka {
            get {
                return ResourceManager.GetString("Natalka_Poltavka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nestor_Litopysec {
            get {
                object obj = ResourceManager.GetObject("Nestor_Litopysec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой Морозе, Морозенку,
        ///Ой да ти славний козаче!
        ///За тобою, Морозенку,
        ///Вся Вкраїна плаче!
        ///
        ///Ой не так же Україна,
        ///Як те горде військо.
        ///Заплакала Морозиха,
        ///Ідучи на місто.
        ///
        ///&quot;Ой не плач же, Морозихо,
        ///Не плач, не журися;
        ///Піди з нами, козаками,
        ///Мед-вина напийся!&quot;
        ///
        ///&quot;Чогось мені, козаченьки,
        ///Мед-вино не п’ється:
        ///Десь мій син Морозенко
        ///З татарами б’ється!&quot;
        ///
        ///Із-за гори, із-за кручі
        ///Удале військо виступає,
        ///Попереду Морозенко
        ///Сивим конем виграває.
        ///
        ///Та схилив же голівоньку
        ///Сиву коню аж на гриву,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oi_Moroze_Morozenku {
            get {
                return ResourceManager.GetString("Oi_Moroze_Morozenku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Oles_Honchar {
            get {
                object obj = ResourceManager.GetObject("Oles_Honchar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Olexandr_Dovzhenko {
            get {
                object obj = ResourceManager.GetObject("Olexandr_Dovzhenko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Olexandr_Oles {
            get {
                object obj = ResourceManager.GetObject("Olexandr_Oles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Olha_Cobylanska {
            get {
                object obj = ResourceManager.GetObject("Olha_Cobylanska", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ostap_Vyshna {
            get {
                object obj = ResourceManager.GetObject("Ostap_Vyshna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Panas_Myrnui {
            get {
                object obj = ResourceManager.GetObject("Panas_Myrnui", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Panteleimon_Kulish {
            get {
                object obj = ResourceManager.GetObject("Panteleimon_Kulish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperBackground {
            get {
                object obj = ResourceManager.GetObject("PaperBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pavlo_Tychyna {
            get {
                object obj = ResourceManager.GetObject("Pavlo_Tychyna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil_over {
            get {
                object obj = ResourceManager.GetObject("pencil_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap progress {
            get {
                object obj = ResourceManager.GetObject("progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap research {
            get {
                object obj = ResourceManager.GetObject("research", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як краще розповісти про похід Ігорів — за зразком давнього співця Бояна чи за вимогами сучасності? Ігор Святославович укріпив ум силою, а серце вигострив мужністю й повів свої хоробрі полки на землю Половецьку за землю Руську.
        ///
        ///Ігор чекає свого брата Всеволода. А в того вже бистрі коні осідлані стоять під Курськом, воїни вправні, шукають собі честі, а князю — слави.
        ///
        ///Глянув Ігор на світле сонце, а воно тьмою закрилося. Сказав князь воїнам: &quot;Браття і дружино! Краще полягти в бою, ніж потрапити в полон. Х [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Slovo_pro_pohid_Igoriv {
            get {
                return ResourceManager.GetString("Slovo_pro_pohid_Igoriv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap statistics {
            get {
                object obj = ResourceManager.GetObject("statistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Taras_Shevchenko {
            get {
                object obj = ResourceManager.GetObject("Taras_Shevchenko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap theory {
            get {
                object obj = ResourceManager.GetObject("theory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Valerian_Pidmohylnui {
            get {
                object obj = ResourceManager.GetObject("Valerian_Pidmohylnui", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vasyl_Stefanyk {
            get {
                object obj = ResourceManager.GetObject("Vasyl_Stefanyk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vasyl_Stus {
            get {
                object obj = ResourceManager.GetObject("Vasyl_Stus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всякому місту – звичай і права,
        ///Всяка тримає свій ум голова;
        ///Всякому серцю – любов і тепло,
        ///Всякеє горло свій смак віднайшло.
        ///Я ж у полоні нав’язливих дум:
        ///Лише одне непокоїть мій ум.
        ///
        ///Панські Петро для чинів тре кутки,
        ///Федір-купець обдурити прудкий,
        ///Той зводить дім свій на модний манір,
        ///Інший гендлює, візьми перевір!
        ///Я ж у полоні нав’язливих дум:
        ///Лише одне непокоїть мій ум.
        ///
        ///Той безперервно стягає поля,
        ///Сей іноземних заводить телят.
        ///Ті на ловецтво готують собак,
        ///В сих дім, як вулик, гуде в [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vsyacomu_mistu_zvuchai_i_prava {
            get {
                return ResourceManager.GetString("Vsyacomu_mistu_zvuchai_i_prava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yuriy_Yanovskiy {
            get {
                object obj = ResourceManager.GetObject("Yuriy_Yanovskiy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
